### ISSUE TITLE
Auto generate the chnagelog from the git history

### ISSUE THREAD

**Issue by krasi-georgiev** [DAmNRelentless/vscode-keepachangelog#2]
It would be nice to be able to auto generate a changelog entry for a release from a git history.

Select a commit or a tag and the extension just extracts all commit messages to generate the release changelog entry.

**Comment by rlnt** [comment]
Feature Request template not used.

Furthermore, this feature does not really fit into a snippet extension. This should be a standalone extension.
We currently don't plan to add this. This extension is just for snippets to have a faster workflow.
