### ISSUE TITLE
Generated markdown does not pass lint test

### ISSUE THREAD

**Issue by rcdailey** [DAmNRelentless/vscode-keepachangelog#5]
There are some minor formatting issues with the generated markdown. Mainly has to do with insufficient newlines.

Tests were performed with the [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) extension installed in VS Code. I also edit my `CHANGELOG.md` file in VS Code.

# Steps to reproduce

1. Open your `MARKDOWN.md` file in VS Code.
2. Put your caret after the `[Unreleased]` header, as shown in FIGURE1 (at the bottom of this issue).
3. Type `c`, then CTRL+SPACE (to auto-complete) and select `cl-added`. Press ENTER.

The generated markdown (FIGURE2 below) has several markdown lint violations of type [MD022](https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md022)/blanks-around-headings/blanks-around-headers:

> Headings should be surrounded by blank lines

# Expected Output

The markdown (based on FIGURE2) that is expected is below:

```md
## [Unreleased]

### Added

-

### Changed

- Unrecognized or unwanted YAML properties in configuration YAML (`trash.yml`) now result in an
  error. This is to help users more easily identify mistakes.
```

Specifically:

- A blank line between `## [Unreleased]` and `### Added`
- A blank line between `### Added` and `-` (the first bullet point item in the list of added items)
- A blank line between the `-` and the next section header, which is `### Changed` in my case.

# Supporting Attachments

FIGURE1:

![image](https://user-images.githubusercontent.com/1768054/156855381-ce015884-1419-4964-8d64-9f40b2c63b76.png)

FIGURE2:

![image](https://user-images.githubusercontent.com/1768054/156855559-8bdddde5-0d28-4964-ba7d-1bfd5424c9d7.png)

**Comment by rlnt** [comment]
This extension provides snippets that respect the ruleset of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) and does not take any linter into account.
As you can see on their page, they also don't have newlines at the positions you mentioned.

If you scroll down to their QnA and read the `Is there a standard changelog format?`, you will see that they didn't create it with a special format in mind.
This issue is out of scope since the extension does exactly what it is advertised to do.

The only thing I could do is to add an extension option to add newlines around headers but that won't be enabled by default.
If that's not an option for you, I'm sorry but I won't change anything else.

**Comment by rcdailey** [comment]
If they didn't create it with a special format in mind, that means there should be no issue with you altering the whitespace in the template, right?

A setting would be great if that's all you're willing to do. At the end of the day, my changelog is a markdown file like any other. The keep a changelog guidelines are not violated when manipulating whitespace, IMHO. The rationale listed for this markdown rule also makes this somewhat a functional issue as well:

> Rationale: Aside from aesthetic reasons, some parsers, including kramdown, will not parse headers that don't have a blank line before, and will parse them as regular text.

Thanks for the quick response!

**Comment by rcdailey** [comment]
Looking at the code, would it be reasonable to just have the snippets themselves in settings so folks can edit them however they want?

**Comment by rlnt** [comment]
~~I am not planning to do that. I'm just not having so much time on my hands right now.~~
If you want to have something like this, feel free to fork the project and compile your own version of it. It's LGPL-licensed and you can create your own extension.

Edit: implemented as default behavior
